//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//
import {Warehouse} from '../warehouse/warehouse';

export class Goods {
    // Raw attributes
    id : number;
    name : string;
    description : string;
    creationDate : Date;
    creationAuthor : string;
    lastModificationDate : Date;
    lastModificationAuthor : string;
    version : number;
    // many-to-many
    theWarehouses : Warehouse[];


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.name = json.name;
            this.description = json.description;
            if (json.creationDate != null) {
                this.creationDate = new Date(json.creationDate);
            }
            this.creationAuthor = json.creationAuthor;
            if (json.lastModificationDate != null) {
                this.lastModificationDate = new Date(json.lastModificationDate);
            }
            this.lastModificationAuthor = json.lastModificationAuthor;
            this.version = json.version;

            if (json.theWarehouses != null) {
                this.theWarehouses = Warehouse.toArray(json.theWarehouses);
            }
        }
    }

    // Utils

    static toArray(jsons : any[]) : Goods[] {
        let goodss : Goods[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                goodss.push(new Goods(json));
            }
        }
        return goodss;
    }
}
