//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {Goods} from './goods';
import {GoodsService} from './goods.service';
import {Warehouse} from '../warehouse/warehouse';
import {WarehouseService} from '../warehouse/warehouse.service';

@Component({
    moduleId: module.id,
	templateUrl: 'goods-detail.component.html',
	selector: 'goods-detail',
})
export class GoodsDetailComponent implements OnInit, OnDestroy {
    goods : Goods;

    private params_subscription: any;

    sourceTheWarehouses : Warehouse[] = [];

    @Input() sub : boolean = false;
    @Output() onSaveClicked = new EventEmitter<Goods>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private goodsService: GoodsService, private warehouseService : WarehouseService) {
        warehouseService.complete(null).
            subscribe(theWarehouses => this.sourceTheWarehouses = theWarehouses,
                        error =>  this.messageService.error('Constructor error', error));
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for goods-detail ' + id);

            if (id === 'new') {
                this.goods = new Goods();
            } else {
                this.goodsService.getGoods(id)
                    .subscribe(goods => {
                            this.goods = goods;
                            this.sourceTheWarehouses = this.sourceTheWarehouses.filter(item => this.goods.theWarehouses.map((e) => e.id).indexOf(item.id) < 0);
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    onSave() {
        this.goodsService.update(this.goods).
            subscribe(
                goods => {
                    this.goods = goods;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.goods);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
