//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { WarehouseServiceProvider } from './warehouseServiceProvider';
import { Observable } from 'rxjs/Rx';
import { catchError, map } from 'rxjs/operators';
import 'rxjs/add/observable/throw';

@Injectable()
export class WarehouseServiceProviderService {

    constructor(private http: HttpClient, private messageService : MessageService) {}

    /**
     * Get a WarehouseServiceProvider by id.
     */
    getWarehouseServiceProvider(id : any) : Observable<WarehouseServiceProvider> {
        return this.http.get('/api/warehouseServiceProviders/' + id)
            .pipe(
                map(response => new WarehouseServiceProvider(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Update the passed warehouseServiceProvider.
     */
    update(warehouseServiceProvider : WarehouseServiceProvider) : Observable<WarehouseServiceProvider> {
        let body = warehouseServiceProvider;

        return this.http.put('/api/warehouseServiceProviders/', body)
            .pipe(
                map(response => new WarehouseServiceProvider(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Load a page (for paginated datatable) of WarehouseServiceProvider using the passed
     * warehouseServiceProvider as an example for the search by example facility.
     */
    getPage(warehouseServiceProvider : WarehouseServiceProvider, event : LazyLoadEvent) : Observable<PageResponse<WarehouseServiceProvider>> {
        let req = new PageRequestByExample(warehouseServiceProvider, event);
        let body = req;

        return this.http.post<PageResponse<any>>('/api/warehouseServiceProviders/page', body)
            .pipe(
                map(pr =>  new PageResponse<WarehouseServiceProvider>(pr.totalPages, pr.totalElements, WarehouseServiceProvider.toArray(pr.content))),
                catchError(this.handleError)
            );
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by WarehouseServiceProviderCompleteComponent.
     */
    complete(query : string) : Observable<WarehouseServiceProvider[]> {
        let body = {'query': query, 'maxResults': 10};
        return this.http.post<any[]>('/api/warehouseServiceProviders/complete', body)
            .pipe(
                map(response => WarehouseServiceProvider.toArray(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Delete an WarehouseServiceProvider by id.
     */
    delete(id : any) {
        return this.http.delete('/api/warehouseServiceProviders/' + id)
            .pipe(catchError(this.handleError));
    }

    // sample method from angular doc
    private handleError (error: HttpErrorResponse) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message : 'Server error';
        console.error(errMsg);
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
