//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//
import {WarehouseServiceProviderPk} from "./warehouseServiceProviderPk";
import {User} from '../user/user';
import {Warehouse} from '../warehouse/warehouse';

export class WarehouseServiceProvider {
    id : WarehouseServiceProviderPk = new WarehouseServiceProviderPk();
    // Raw attributes
    creationDate : Date;
    creationAuthor : string;
    lastModificationDate : Date;
    lastModificationAuthor : string;
    version : number;
    // x-to-one
    user : User;
    warehouse : Warehouse;


    constructor(json? : any) {
        if (json != null) {
            this.id = new WarehouseServiceProviderPk(json.id);
            if (json.creationDate != null) {
                this.creationDate = new Date(json.creationDate);
            }
            this.creationAuthor = json.creationAuthor;
            if (json.lastModificationDate != null) {
                this.lastModificationDate = new Date(json.lastModificationDate);
            }
            this.lastModificationAuthor = json.lastModificationAuthor;
            this.version = json.version;

            if (json.user != null) {
                this.user = new User(json.user);
            }

            if (json.warehouse != null) {
                this.warehouse = new Warehouse(json.warehouse);
            }
        }
    }

    // Utils

    static toArray(jsons : any[]) : WarehouseServiceProvider[] {
        let warehouseServiceProviders : WarehouseServiceProvider[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                warehouseServiceProviders.push(new WarehouseServiceProvider(json));
            }
        }
        return warehouseServiceProviders;
    }
}
