/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.mycompany.myapp.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.mycompany.myapp.domain.Databasechangeloglock;
import com.mycompany.myapp.dto.DatabasechangeloglockDTO;
import com.mycompany.myapp.dto.DatabasechangeloglockDTOService;
import com.mycompany.myapp.dto.support.PageRequestByExample;
import com.mycompany.myapp.dto.support.PageResponse;
import com.mycompany.myapp.repository.DatabasechangeloglockRepository;
import com.mycompany.myapp.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/databasechangeloglocks")
public class DatabasechangeloglockResource {

    private final Logger log = LoggerFactory.getLogger(DatabasechangeloglockResource.class);

    @Inject
    private DatabasechangeloglockRepository databasechangeloglockRepository;
    @Inject
    private DatabasechangeloglockDTOService databasechangeloglockDTOService;

    /**
     * Create a new Databasechangeloglock.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<DatabasechangeloglockDTO> create(@RequestBody DatabasechangeloglockDTO databasechangeloglockDTO) throws URISyntaxException {

        log.debug("Create DatabasechangeloglockDTO : {}", databasechangeloglockDTO);

        if (databasechangeloglockDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create Databasechangeloglock with existing ID").body(null);
        }

        DatabasechangeloglockDTO result = databasechangeloglockDTOService.save(databasechangeloglockDTO);

        return ResponseEntity.created(new URI("/api/databasechangeloglocks/" + result.id)).body(result);
    }

    /**
    * Find by id Databasechangeloglock.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<DatabasechangeloglockDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id Databasechangeloglock : {}", id);

        return Optional.ofNullable(databasechangeloglockDTOService.findOne(id))
                .map(databasechangeloglockDTO -> new ResponseEntity<>(databasechangeloglockDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update Databasechangeloglock.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<DatabasechangeloglockDTO> update(@RequestBody DatabasechangeloglockDTO databasechangeloglockDTO) throws URISyntaxException {

        log.debug("Update DatabasechangeloglockDTO : {}", databasechangeloglockDTO);

        if (!databasechangeloglockDTO.isIdSet()) {
            return create(databasechangeloglockDTO);
        }

        DatabasechangeloglockDTO result = databasechangeloglockDTOService.save(databasechangeloglockDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of Databasechangeloglock using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<DatabasechangeloglockDTO>> findAll(@RequestBody PageRequestByExample<DatabasechangeloglockDTO> prbe)
            throws URISyntaxException {
        PageResponse<DatabasechangeloglockDTO> pageResponse = databasechangeloglockDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<DatabasechangeloglockDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<DatabasechangeloglockDTO> results = databasechangeloglockDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id Databasechangeloglock.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id Databasechangeloglock : {}", id);

        try {
            databasechangeloglockRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}