/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.mycompany.myapp.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.mycompany.myapp.domain.Enquiry;
import com.mycompany.myapp.dto.EnquiryDTO;
import com.mycompany.myapp.dto.EnquiryDTOService;
import com.mycompany.myapp.dto.support.PageRequestByExample;
import com.mycompany.myapp.dto.support.PageResponse;
import com.mycompany.myapp.repository.EnquiryRepository;
import com.mycompany.myapp.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/pages/enquiries")
public class EnquiryResource {

    private final Logger log = LoggerFactory.getLogger(EnquiryResource.class);

    @Inject
    private EnquiryRepository enquiryRepository;
    @Inject
    private EnquiryDTOService enquiryDTOService;

    /**
     * Create a new Enquiry.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<EnquiryDTO> create(@RequestBody EnquiryDTO enquiryDTO) throws URISyntaxException {

        log.debug("Create EnquiryDTO : {}", enquiryDTO);

        if (enquiryDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create Enquiry with existing ID").body(null);
        }

        EnquiryDTO result = enquiryDTOService.save(enquiryDTO);

        return ResponseEntity.created(new URI("/api/enquiries/" + result.id)).body(result);
    }

    /**
    * Find by id Enquiry.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<EnquiryDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id Enquiry : {}", id);

        return Optional.ofNullable(enquiryDTOService.findOne(id)).map(enquiryDTO -> new ResponseEntity<>(enquiryDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update Enquiry.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<EnquiryDTO> update(@RequestBody EnquiryDTO enquiryDTO) throws URISyntaxException {

        log.debug("Update EnquiryDTO : {}", enquiryDTO);

        if (!enquiryDTO.isIdSet()) {
            return create(enquiryDTO);
        }

        EnquiryDTO result = enquiryDTOService.save(enquiryDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of Enquiry using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<EnquiryDTO>> findAll(@RequestBody PageRequestByExample<EnquiryDTO> prbe) throws URISyntaxException {
        PageResponse<EnquiryDTO> pageResponse = enquiryDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<EnquiryDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<EnquiryDTO> results = enquiryDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id Enquiry.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id Enquiry : {}", id);

        try {
            enquiryRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}