/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.mycompany.myapp.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.mycompany.myapp.domain.Order;
import com.mycompany.myapp.dto.OrderDTO;
import com.mycompany.myapp.dto.OrderDTOService;
import com.mycompany.myapp.dto.support.PageRequestByExample;
import com.mycompany.myapp.dto.support.PageResponse;
import com.mycompany.myapp.repository.OrderRepository;
import com.mycompany.myapp.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/orders")
public class OrderResource {

    private final Logger log = LoggerFactory.getLogger(OrderResource.class);

    @Inject
    private OrderRepository orderRepository;
    @Inject
    private OrderDTOService orderDTOService;

    /**
     * Create a new Order.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<OrderDTO> create(@RequestBody OrderDTO orderDTO) throws URISyntaxException {

        log.debug("Create OrderDTO : {}", orderDTO);

        if (orderDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create Order with existing ID").body(null);
        }

        OrderDTO result = orderDTOService.save(orderDTO);

        return ResponseEntity.created(new URI("/api/orders/" + result.id)).body(result);
    }

    /**
    * Find by id Order.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<OrderDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id Order : {}", id);

        return Optional.ofNullable(orderDTOService.findOne(id)).map(orderDTO -> new ResponseEntity<>(orderDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update Order.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<OrderDTO> update(@RequestBody OrderDTO orderDTO) throws URISyntaxException {

        log.debug("Update OrderDTO : {}", orderDTO);

        if (!orderDTO.isIdSet()) {
            return create(orderDTO);
        }

        OrderDTO result = orderDTOService.save(orderDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of Order using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<OrderDTO>> findAll(@RequestBody PageRequestByExample<OrderDTO> prbe) throws URISyntaxException {
        PageResponse<OrderDTO> pageResponse = orderDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<OrderDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<OrderDTO> results = orderDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id Order.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id Order : {}", id);

        try {
            orderRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}