/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.mycompany.myapp.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.mycompany.myapp.domain.Rate;
import com.mycompany.myapp.dto.RateDTO;
import com.mycompany.myapp.dto.RateDTOService;
import com.mycompany.myapp.dto.support.PageRequestByExample;
import com.mycompany.myapp.dto.support.PageResponse;
import com.mycompany.myapp.repository.RateRepository;
import com.mycompany.myapp.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/rates")
public class RateResource {

    private final Logger log = LoggerFactory.getLogger(RateResource.class);

    @Inject
    private RateRepository rateRepository;
    @Inject
    private RateDTOService rateDTOService;

    /**
     * Create a new Rate.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<RateDTO> create(@RequestBody RateDTO rateDTO) throws URISyntaxException {

        log.debug("Create RateDTO : {}", rateDTO);

        if (rateDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create Rate with existing ID").body(null);
        }

        RateDTO result = rateDTOService.save(rateDTO);

        return ResponseEntity.created(new URI("/api/rates/" + result.id)).body(result);
    }

    /**
    * Find by id Rate.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<RateDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id Rate : {}", id);

        return Optional.ofNullable(rateDTOService.findOne(id)).map(rateDTO -> new ResponseEntity<>(rateDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update Rate.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<RateDTO> update(@RequestBody RateDTO rateDTO) throws URISyntaxException {

        log.debug("Update RateDTO : {}", rateDTO);

        if (!rateDTO.isIdSet()) {
            return create(rateDTO);
        }

        RateDTO result = rateDTOService.save(rateDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of Rate using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<RateDTO>> findAll(@RequestBody PageRequestByExample<RateDTO> prbe) throws URISyntaxException {
        PageResponse<RateDTO> pageResponse = rateDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<RateDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<RateDTO> results = rateDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id Rate.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id Rate : {}", id);

        try {
            rateRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}