/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.mycompany.myapp.rest;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Optional;

import javax.inject.Inject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestBody;

import com.mycompany.myapp.domain.WarehouseReview;
import com.mycompany.myapp.dto.WarehouseReviewDTO;
import com.mycompany.myapp.dto.WarehouseReviewDTOService;
import com.mycompany.myapp.dto.support.PageRequestByExample;
import com.mycompany.myapp.dto.support.PageResponse;
import com.mycompany.myapp.repository.WarehouseReviewRepository;
import com.mycompany.myapp.rest.support.AutoCompleteQuery;

@RestController
@RequestMapping("/api/warehouseReviews")
public class WarehouseReviewResource {

    private final Logger log = LoggerFactory.getLogger(WarehouseReviewResource.class);

    @Inject
    private WarehouseReviewRepository warehouseReviewRepository;
    @Inject
    private WarehouseReviewDTOService warehouseReviewDTOService;

    /**
     * Create a new WarehouseReview.
     */
    @RequestMapping(value = "/", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<WarehouseReviewDTO> create(@RequestBody WarehouseReviewDTO warehouseReviewDTO) throws URISyntaxException {

        log.debug("Create WarehouseReviewDTO : {}", warehouseReviewDTO);

        if (warehouseReviewDTO.isIdSet()) {
            return ResponseEntity.badRequest().header("Failure", "Cannot create WarehouseReview with existing ID").body(null);
        }

        WarehouseReviewDTO result = warehouseReviewDTOService.save(warehouseReviewDTO);

        return ResponseEntity.created(new URI("/api/warehouseReviews/" + result.id)).body(result);
    }

    /**
    * Find by id WarehouseReview.
    */
    @RequestMapping(value = "/{id}", method = GET, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<WarehouseReviewDTO> findById(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Find by id WarehouseReview : {}", id);

        return Optional.ofNullable(warehouseReviewDTOService.findOne(id)).map(warehouseReviewDTO -> new ResponseEntity<>(warehouseReviewDTO, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

    /**
     * Update WarehouseReview.
     */
    @RequestMapping(value = "/", method = PUT, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<WarehouseReviewDTO> update(@RequestBody WarehouseReviewDTO warehouseReviewDTO) throws URISyntaxException {

        log.debug("Update WarehouseReviewDTO : {}", warehouseReviewDTO);

        if (!warehouseReviewDTO.isIdSet()) {
            return create(warehouseReviewDTO);
        }

        WarehouseReviewDTO result = warehouseReviewDTOService.save(warehouseReviewDTO);

        return ResponseEntity.ok().body(result);
    }

    /**
     * Find a Page of WarehouseReview using query by example.
     */
    @RequestMapping(value = "/page", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<PageResponse<WarehouseReviewDTO>> findAll(@RequestBody PageRequestByExample<WarehouseReviewDTO> prbe) throws URISyntaxException {
        PageResponse<WarehouseReviewDTO> pageResponse = warehouseReviewDTOService.findAll(prbe);
        return new ResponseEntity<>(pageResponse, new HttpHeaders(), HttpStatus.OK);
    }

    /**
    * Auto complete support.
    */
    @RequestMapping(value = "/complete", method = POST, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<List<WarehouseReviewDTO>> complete(@RequestBody AutoCompleteQuery acq) throws URISyntaxException {

        List<WarehouseReviewDTO> results = warehouseReviewDTOService.complete(acq.query, acq.maxResults);

        return new ResponseEntity<>(results, new HttpHeaders(), HttpStatus.OK);
    }

    /**
     * Delete by id WarehouseReview.
     */
    @RequestMapping(value = "/{id}", method = DELETE, produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Void> delete(@PathVariable Integer id) throws URISyntaxException {

        log.debug("Delete by id WarehouseReview : {}", id);

        try {
            warehouseReviewRepository.delete(id);
            return ResponseEntity.ok().build();
        } catch (Exception x) {
            // todo: dig exception, most likely org.hibernate.exception.ConstraintViolationException
            return ResponseEntity.status(HttpStatus.CONFLICT).build();
        }
    }
}