//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//

export class Databasechangeloglock {
    // Raw attributes
    id : number;
    locked : boolean;
    lockedby : string;
    lockgranted : Date;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.locked = json.locked;
            this.lockedby = json.lockedby;
            if (json.lockgranted != null) {
                this.lockgranted = new Date(json.lockgranted);
            }
        }
    }

    // Utils

    static toArray(jsons : any[]) : Databasechangeloglock[] {
        let databasechangeloglocks : Databasechangeloglock[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                databasechangeloglocks.push(new Databasechangeloglock(json));
            }
        }
        return databasechangeloglocks;
    }
}
