//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { Databasechangeloglock } from './databasechangeloglock';
import { Observable } from 'rxjs/Rx';
import { catchError, map } from 'rxjs/operators';
import 'rxjs/add/observable/throw';

@Injectable()
export class DatabasechangeloglockService {

    constructor(private http: HttpClient, private messageService : MessageService) {}

    /**
     * Get a Databasechangeloglock by id.
     */
    getDatabasechangeloglock(id : any) : Observable<Databasechangeloglock> {
        return this.http.get('/api/databasechangeloglocks/' + id)
            .pipe(
                map(response => new Databasechangeloglock(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Update the passed databasechangeloglock.
     */
    update(databasechangeloglock : Databasechangeloglock) : Observable<Databasechangeloglock> {
        let body = databasechangeloglock;

        return this.http.put('/api/databasechangeloglocks/', body)
            .pipe(
                map(response => new Databasechangeloglock(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Load a page (for paginated datatable) of Databasechangeloglock using the passed
     * databasechangeloglock as an example for the search by example facility.
     */
    getPage(databasechangeloglock : Databasechangeloglock, event : LazyLoadEvent) : Observable<PageResponse<Databasechangeloglock>> {
        let req = new PageRequestByExample(databasechangeloglock, event);
        let body = req;

        return this.http.post<PageResponse<any>>('/api/databasechangeloglocks/page', body)
            .pipe(
                map(pr =>  new PageResponse<Databasechangeloglock>(pr.totalPages, pr.totalElements, Databasechangeloglock.toArray(pr.content))),
                catchError(this.handleError)
            );
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by DatabasechangeloglockCompleteComponent.
     */
    complete(query : string) : Observable<Databasechangeloglock[]> {
        let body = {'query': query, 'maxResults': 10};
        return this.http.post<any[]>('/api/databasechangeloglocks/complete', body)
            .pipe(
                map(response => Databasechangeloglock.toArray(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Delete an Databasechangeloglock by id.
     */
    delete(id : any) {
        return this.http.delete('/api/databasechangeloglocks/' + id)
            .pipe(catchError(this.handleError));
    }

    // sample method from angular doc
    private handleError (error: HttpErrorResponse) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message : 'Server error';
        console.error(errMsg);
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
