//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//

export class Order {
    // Raw attributes
    id : number;
    orderDate : Date;
    creationDate : Date;
    creationAuthor : string;
    lastModificationDate : Date;
    lastModificationAuthor : string;
    version : number;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            if (json.orderDate != null) {
                this.orderDate = new Date(json.orderDate);
            }
            if (json.creationDate != null) {
                this.creationDate = new Date(json.creationDate);
            }
            this.creationAuthor = json.creationAuthor;
            if (json.lastModificationDate != null) {
                this.lastModificationDate = new Date(json.lastModificationDate);
            }
            this.lastModificationAuthor = json.lastModificationAuthor;
            this.version = json.version;
        }
    }

    // Utils

    static toArray(jsons : any[]) : Order[] {
        let orders : Order[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                orders.push(new Order(json));
            }
        }
        return orders;
    }
}
