/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.mycompany.myapp.repository;

import java.util.List;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.repository.*;

import com.mycompany.myapp.domain.Passport;
import com.mycompany.myapp.domain.Passport_;

public interface PassportRepository extends JpaRepository<Passport, Integer> {

    /**
     * Return the persistent instance of {@link Passport} with the given unique property value holderId,
     * or null if there is no such persistent instance.
     *
     * @param holderId the unique value
     * @return the corresponding {@link Passport} persistent instance or null
     */
    Passport getByHolderId(Integer holderId);

    default List<Passport> complete(String query, int maxResults) {
        Passport probe = new Passport();

        ExampleMatcher matcher = ExampleMatcher.matching() //
        ;

        Page<Passport> page = findAll(Example.of(probe, matcher), new PageRequest(0, maxResults));
        return page.getContent();
    }
}