//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { Enquiry } from './enquiry';
import { Observable } from 'rxjs/Rx';
import { catchError, map } from 'rxjs/operators';
import 'rxjs/add/observable/throw';

@Injectable()
export class EnquiryService {

    constructor(private http: HttpClient, private messageService : MessageService) {}

    /**
     * Get a Enquiry by id.
     */
    getEnquiry(id : any) : Observable<Enquiry> {
        return this.http.get('/api/enquiries/' + id)
            .pipe(
                map(response => new Enquiry(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Update the passed enquiry.
     */
    update(enquiry : Enquiry) : Observable<Enquiry> {
        let body = enquiry;

        return this.http.put('/api/enquiries/', body)
            .pipe(
                map(response => new Enquiry(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Load a page (for paginated datatable) of Enquiry using the passed
     * enquiry as an example for the search by example facility.
     */
    getPage(enquiry : Enquiry, event : LazyLoadEvent) : Observable<PageResponse<Enquiry>> {
        let req = new PageRequestByExample(enquiry, event);
        let body = req;

        return this.http.post<PageResponse<any>>('/api/enquiries/page', body)
            .pipe(
                map(pr =>  new PageResponse<Enquiry>(pr.totalPages, pr.totalElements, Enquiry.toArray(pr.content))),
                catchError(this.handleError)
            );
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by EnquiryCompleteComponent.
     */
    complete(query : string) : Observable<Enquiry[]> {
        let body = {'query': query, 'maxResults': 10};
        return this.http.post<any[]>('/api/enquiries/complete', body)
            .pipe(
                map(response => Enquiry.toArray(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Delete an Enquiry by id.
     */
    delete(id : any) {
        return this.http.delete('/api/enquiries/' + id)
            .pipe(catchError(this.handleError));
    }

    // sample method from angular doc
    private handleError (error: HttpErrorResponse) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message : 'Server error';
        console.error(errMsg);
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
