//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {Enquiry} from './enquiry';
import {EnquiryService} from './enquiry.service';
import {User} from '../user/user';
import {Warehouse} from '../warehouse/warehouse';

@Component({
    moduleId: module.id,
	templateUrl: 'enquiry-detail.component.html',
	selector: 'enquiry-detail',
})
export class EnquiryDetailComponent implements OnInit, OnDestroy {
    enquiry : Enquiry;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Input() // used to pass the parent when creating a new Enquiry
    set user(user : User) {
        this.enquiry = new Enquiry();
        this.enquiry.user = user;
    }

    @Input() // used to pass the parent when creating a new Enquiry
    set warehouse(warehouse : Warehouse) {
        this.enquiry = new Enquiry();
        this.enquiry.warehouse = warehouse;
    }

    @Output() onSaveClicked = new EventEmitter<Enquiry>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private enquiryService: EnquiryService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for enquiry-detail ' + id);

            if (id === 'new') {
                this.enquiry = new Enquiry();
            } else {
                this.enquiryService.getEnquiry(id)
                    .subscribe(enquiry => {
                            this.enquiry = enquiry;
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    gotoUser() {
        this.router.navigate(['/user', this.enquiry.user.id]);
    }

    clearUser() {
        this.enquiry.user = null;
    }

    gotoWarehouse() {
        this.router.navigate(['/warehouse', this.enquiry.warehouse.id]);
    }

    clearWarehouse() {
        this.enquiry.warehouse = null;
    }

    onSave() {
        this.enquiryService.update(this.enquiry).
            subscribe(
                enquiry => {
                    this.enquiry = enquiry;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.enquiry);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
