//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//
import {User} from '../user/user';

export class WarehouseReview {
    // Raw attributes
    id : number;
    overallRating : number;
    turnaroundTime : number;
    responsiveness : string;
    comments : string;
    creationDate : Date;
    creationAuthor : string;
    lastModificationDate : Date;
    lastModificationAuthor : string;
    version : number;
    // x-to-one
    user : User;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.overallRating = json.overallRating;
            this.turnaroundTime = json.turnaroundTime;
            this.responsiveness = json.responsiveness;
            this.comments = json.comments;
            if (json.creationDate != null) {
                this.creationDate = new Date(json.creationDate);
            }
            this.creationAuthor = json.creationAuthor;
            if (json.lastModificationDate != null) {
                this.lastModificationDate = new Date(json.lastModificationDate);
            }
            this.lastModificationAuthor = json.lastModificationAuthor;
            this.version = json.version;

            if (json.user != null) {
                this.user = new User(json.user);
            }
        }
    }

    // Utils

    static toArray(jsons : any[]) : WarehouseReview[] {
        let warehouseReviews : WarehouseReview[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                warehouseReviews.push(new WarehouseReview(json));
            }
        }
        return warehouseReviews;
    }
}
