//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {WarehouseReview} from './warehouseReview';
import {WarehouseReviewService} from './warehouseReview.service';
import {User} from '../user/user';

@Component({
    moduleId: module.id,
	templateUrl: 'warehouseReview-detail.component.html',
	selector: 'warehouseReview-detail',
})
export class WarehouseReviewDetailComponent implements OnInit, OnDestroy {
    warehouseReview : WarehouseReview;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Input() // used to pass the parent when creating a new WarehouseReview
    set user(user : User) {
        this.warehouseReview = new WarehouseReview();
        this.warehouseReview.user = user;
    }

    @Output() onSaveClicked = new EventEmitter<WarehouseReview>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private warehouseReviewService: WarehouseReviewService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for warehouseReview-detail ' + id);

            if (id === 'new') {
                this.warehouseReview = new WarehouseReview();
            } else {
                this.warehouseReviewService.getWarehouseReview(id)
                    .subscribe(warehouseReview => {
                            this.warehouseReview = warehouseReview;
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    gotoUser() {
        this.router.navigate(['/user', this.warehouseReview.user.id]);
    }

    clearUser() {
        this.warehouseReview.user = null;
    }

    onSave() {
        this.warehouseReviewService.update(this.warehouseReview).
            subscribe(
                warehouseReview => {
                    this.warehouseReview = warehouseReview;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.warehouseReview);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
