---
#
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#

server:
    port: 8081

security:
    basic:
        enabled: false

# Note: the properties surounded by arobase are defined in the pom.xml file
#       and get replaced by maven during build time. Resulting file can
#       be found in target/classes folder

spring:

    datasource:
        driver-class-name: @jdbc.driver@
        url: @jdbc.url@
        name:
        username: @jdbc.user@
        password: @jdbc.password@

    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

        database-platform: @hibernate.dialect@
        database: postgresql
        show_sql: true
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false

    mail:
        host: smtp.zoho.com
        username: ajay.anand10@zoho.com
        password: kalyan@10
        port: 587
        protocol: smtp
        tls: true
        properties.mail.smtp:
          auth: true
          starttls.enable: true    
       



    messages:
        cache-seconds: 1

    resources:
        chain:
            cache: false

---

#
# profile used by Dockerfile... just for convenient demo
#
spring.profiles: demowithdocker
spring.datasource.url: jdbc:h2:/db/angulardb;MVCC=TRUE;FILE_LOCK=NO
