//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {Databasechangelog} from './databasechangelog';
import {DatabasechangelogService} from './databasechangelog.service';

@Component({
    moduleId: module.id,
	templateUrl: 'databasechangelog-detail.component.html',
	selector: 'databasechangelog-detail',
})
export class DatabasechangelogDetailComponent implements OnInit, OnDestroy {
    databasechangelog : Databasechangelog;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Output() onSaveClicked = new EventEmitter<Databasechangelog>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private databasechangelogService: DatabasechangelogService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for databasechangelog-detail ' + id);

            if (id === 'new') {
                this.databasechangelog = new Databasechangelog();
            } else {
                this.databasechangelogService.getDatabasechangelog(id)
                    .subscribe(databasechangelog => {
                            this.databasechangelog = databasechangelog;
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    onSave() {
        this.databasechangelogService.update(this.databasechangelog).
            subscribe(
                databasechangelog => {
                    this.databasechangelog = databasechangelog;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.databasechangelog);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
