//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity-list.component.ts.e.vm
//
import { Component, Input, Output, OnChanges, EventEmitter, SimpleChanges} from '@angular/core';
import { Router } from '@angular/router';
import { DataTable, LazyLoadEvent } from 'primeng/primeng';
import { PageResponse } from "../../support/paging";
import { MessageService } from '../../service/message.service';
import { MatDialog } from '@angular/material';
import { ConfirmDeleteDialogComponent } from "../../support/confirm-delete-dialog.component";
import { Databasechangelog } from './databasechangelog';
import { DatabasechangelogDetailComponent } from './databasechangelog-detail.component';
import { DatabasechangelogService } from './databasechangelog.service';

@Component({
    moduleId: module.id,
	templateUrl: 'databasechangelog-list.component.html',
	selector: 'databasechangelog-list'
})
export class DatabasechangelogListComponent {

    @Input() header = "Databasechangelogs...";

    // When 'sub' is true, it means this list is used as a one-to-many list.
    // It belongs to a parent entity, as a result the addNew operation
    // must prefill the parent entity. The prefill is not done here, instead we
    // emit an event.
    // When 'sub' is false, we display basic search criterias
    @Input() sub : boolean;
    @Output() onAddNewClicked = new EventEmitter();

    databasechangelogToDelete : Databasechangelog;

    // basic search criterias (visible if not in 'sub' mode)
    example : Databasechangelog = new Databasechangelog();

    // list is paginated
    currentPage : PageResponse<Databasechangelog> = new PageResponse<Databasechangelog>(0,0,[]);


    constructor(private router : Router,
        private databasechangelogService : DatabasechangelogService,
        private messageService : MessageService,
        private confirmDeleteDialog: MatDialog) {
    }

    /**
     * When used as a 'sub' component (to display one-to-many list), refreshes the table
     * content when the input changes.
     */
    ngOnChanges(changes: SimpleChanges) {
        this.loadPage({ first: 0, rows: 10, sortField: null, sortOrder: null, filters: null, multiSortMeta: null });
    }

    /**
     * Invoked when user presses the search button.
     */
    search(dt : DataTable) {
        if (!this.sub) {
            dt.reset();
            this.loadPage({ first: 0, rows: dt.rows, sortField: dt.sortField, sortOrder: dt.sortOrder, filters: null, multiSortMeta: dt.multiSortMeta });
        }
    }

    /**
     * Invoked automatically by primeng datatable.
     */
    loadPage(event : LazyLoadEvent) {
        this.databasechangelogService.getPage(this.example, event).
            subscribe(
                pageResponse => this.currentPage = pageResponse,
                error => this.messageService.error('Could not get the results', error)
            );
    }

    onRowSelect(event : any) {
        let id =  event.data.id;
        this.router.navigate(['/databasechangelog', id]);
    }

    addNew() {
        if (this.sub) {
            this.onAddNewClicked.emit("addNew");
        } else {
            this.router.navigate(['/databasechangelog', 'new']);
        }
    }

    showDeleteDialog(rowData : any) {
        let databasechangelogToDelete : Databasechangelog = <Databasechangelog> rowData;

        let dialogRef = this.confirmDeleteDialog.open(ConfirmDeleteDialogComponent);
        dialogRef.afterClosed().subscribe(result => {
            if (result === 'delete') {
                this.delete(databasechangelogToDelete);
            }
        });
    }

    private delete(databasechangelogToDelete : Databasechangelog) {
        let id =  databasechangelogToDelete.id;

        this.databasechangelogService.delete(id).
            subscribe(
                response => {
                    this.currentPage.remove(databasechangelogToDelete);
                    this.messageService.info('Deleted OK', 'Angular Rocks!');
                },
                error => this.messageService.error('Could not delete!', error)
            );
    }
}