/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.mycompany.myapp.domain;

import java.time.Instant;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Goods.class)
public abstract class Goods_ {

    // Raw attributes
    public static volatile SingularAttribute<Goods, Integer> id;
    public static volatile SingularAttribute<Goods, String> name;
    public static volatile SingularAttribute<Goods, String> description;
    public static volatile SingularAttribute<Goods, Instant> creationDate;
    public static volatile SingularAttribute<Goods, String> creationAuthor;
    public static volatile SingularAttribute<Goods, Instant> lastModificationDate;
    public static volatile SingularAttribute<Goods, String> lastModificationAuthor;
    public static volatile SingularAttribute<Goods, Integer> version;

    // Many to many
    public static volatile ListAttribute<Goods, Warehouse> theWarehouses;
}