/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/CompositePk_.java.cpk.vm
 */
package com.mycompany.myapp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(WarehouseServiceProviderPk.class)
public abstract class WarehouseServiceProviderPk_ {
    // pk attributes
    public static volatile SingularAttribute<WarehouseServiceProviderPk, Integer> warehouseId;
    public static volatile SingularAttribute<WarehouseServiceProviderPk, Integer> userId;
}
