/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.mycompany.myapp.domain;


/**
 * Simple DTO for Warehouse.
 */
public class WarehouseSearchResults {
	
	public Integer id;
    public String name;
    public Double rating;
    public Integer facilitySize;
    public String facilitySizeUom;
    public Integer storageSize;
    public String storageSizeUom;
    public Double storagePrice;
    public String storagePriceUom;
    public String lat;
    public String lng;
    public String type;
	
    
    public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Double getRating() {
		return rating;
	}
	public void setRating(Double rating) {
		this.rating = rating;
	}
	public Integer getFacilitySize() {
		return facilitySize;
	}
	public void setFacilitySize(Integer facilitySize) {
		this.facilitySize = facilitySize;
	}
	public String getFacilitySizeUom() {
		return facilitySizeUom;
	}
	public void setFacilitySizeUom(String facilitySizeUom) {
		this.facilitySizeUom = facilitySizeUom;
	}
	public Integer getStorageSize() {
		return storageSize;
	}
	public void setStorageSize(Integer storageSize) {
		this.storageSize = storageSize;
	}
	public String getStorageSizeUom() {
		return storageSizeUom;
	}
	public void setStorageSizeUom(String storageSizeUom) {
		this.storageSizeUom = storageSizeUom;
	}
	public Double getStoragePrice() {
		return storagePrice;
	}
	public void setStoragePrice(Double storagePrice) {
		this.storagePrice = storagePrice;
	}
	public String getStoragePriceUom() {
		return storagePriceUom;
	}
	public void setStoragePriceUom(String storagePriceUom) {
		this.storagePriceUom = storagePriceUom;
	}
	public String getLat() {
		return lat;
	}
	public void setLat(String lat) {
		this.lat = lat;
	}
	public String getLng() {
		return lng;
	}
	public void setLng(String lng) {
		this.lng = lng;
	}
	
	@Override
	public String toString() {
		return "WarehouseSearchResults [id=" + id + ", name=" + name + ", rating=" + rating + ", facilitySize="
				+ facilitySize + ", facilitySizeUom=" + facilitySizeUom + ", storageSize=" + storageSize
				+ ", storageSizeUom=" + storageSizeUom + ", storagePrice=" + storagePrice + ", storagePriceUom="
				+ storagePriceUom + ", lat=" + lat + ", lng=" + lng + "]";
	}
    
}