/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTOService.java.e.vm
 */
package com.mycompany.myapp.dto;

import java.util.List;
import java.util.stream.Collectors;

import javax.inject.Inject;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.mycompany.myapp.domain.Bookmark;
import com.mycompany.myapp.domain.Bookmark_;
import com.mycompany.myapp.domain.User;
import com.mycompany.myapp.domain.Warehouse;
import com.mycompany.myapp.dto.support.PageRequestByExample;
import com.mycompany.myapp.dto.support.PageResponse;
import com.mycompany.myapp.repository.BookmarkRepository;
import com.mycompany.myapp.repository.UserRepository;
import com.mycompany.myapp.repository.WarehouseRepository;

/**
 * A simple DTO Facility for Bookmark.
 */
@Service
public class BookmarkDTOService {

    @Inject
    private BookmarkRepository bookmarkRepository;
    @Inject
    private UserDTOService userDTOService;
    @Inject
    private UserRepository userRepository;
    @Inject
    private WarehouseDTOService warehouseDTOService;
    @Inject
    private WarehouseRepository warehouseRepository;

    @Transactional(readOnly = true)
    public BookmarkDTO findOne(Integer id) {
        return toDTO(bookmarkRepository.findOne(id));
    }

    @Transactional(readOnly = true)
    public List<BookmarkDTO> complete(String query, int maxResults) {
        List<Bookmark> results = bookmarkRepository.complete(query, maxResults);
        return results.stream().map(this::toDTO).collect(Collectors.toList());
    }

    @Transactional(readOnly = true)
    public PageResponse<BookmarkDTO> findAll(PageRequestByExample<BookmarkDTO> req) {
        Example<Bookmark> example = null;
        Bookmark bookmark = toEntity(req.example);

        if (bookmark != null) {
            ExampleMatcher matcher = ExampleMatcher.matching() //
            ;

            example = Example.of(bookmark, matcher);
        }

        Page<Bookmark> page;
        if (example != null) {
            page = bookmarkRepository.findAll(example, req.toPageable());
        } else {
            page = bookmarkRepository.findAll(req.toPageable());
        }

        List<BookmarkDTO> content = page.getContent().stream().map(this::toDTO).collect(Collectors.toList());
        return new PageResponse<>(page.getTotalPages(), page.getTotalElements(), content);
    }

    /**
     * Save the passed dto as a new entity or update the corresponding entity if any.
     */
    @Transactional
    public BookmarkDTO save(BookmarkDTO dto) {
        if (dto == null) {
            return null;
        }

        final Bookmark bookmark;

        if (dto.isIdSet()) {
            Bookmark bookmarkTmp = bookmarkRepository.findOne(dto.id);
            if (bookmarkTmp != null) {
                bookmark = bookmarkTmp;
            } else {
                bookmark = new Bookmark();
                bookmark.setId(dto.id);
            }
        } else {
            bookmark = new Bookmark();
        }

        bookmark.setCreationDate(dto.creationDate);

        bookmark.setCreationAuthor(dto.creationAuthor);

        bookmark.setLastModificationDate(dto.lastModificationDate);

        bookmark.setLastModificationAuthor(dto.lastModificationAuthor);

        bookmark.setVersion(dto.version);

        if (dto.user == null) {
            bookmark.setUser(null);
        } else {
            User user = bookmark.getUser();
            if (user == null || (user.getId().compareTo(dto.user.id) != 0)) {
                bookmark.setUser(userRepository.findOne(dto.user.id));
            }
        }

        if (dto.warehouse == null) {
            bookmark.setWarehouse(null);
        } else {
            Warehouse warehouse = bookmark.getWarehouse();
            if (warehouse == null || (warehouse.getId().compareTo(dto.warehouse.id) != 0)) {
                bookmark.setWarehouse(warehouseRepository.findOne(dto.warehouse.id));
            }
        }

        return toDTO(bookmarkRepository.save(bookmark));
    }

    /**
     * Converts the passed bookmark to a DTO.
     */
    public BookmarkDTO toDTO(Bookmark bookmark) {
        return toDTO(bookmark, 1);
    }

    /**
     * Converts the passed bookmark to a DTO. The depth is used to control the
     * amount of association you want. It also prevents potential infinite serialization cycles.
     *
     * @param bookmark
     * @param depth the depth of the serialization. A depth equals to 0, means no x-to-one association will be serialized.
     *              A depth equals to 1 means that xToOne associations will be serialized. 2 means, xToOne associations of
     *              xToOne associations will be serialized, etc.
     */
    public BookmarkDTO toDTO(Bookmark bookmark, int depth) {
        if (bookmark == null) {
            return null;
        }

        BookmarkDTO dto = new BookmarkDTO();

        dto.id = bookmark.getId();
        dto.creationDate = bookmark.getCreationDate();
        dto.creationAuthor = bookmark.getCreationAuthor();
        dto.lastModificationDate = bookmark.getLastModificationDate();
        dto.lastModificationAuthor = bookmark.getLastModificationAuthor();
        dto.version = bookmark.getVersion();
        if (depth-- > 0) {
            dto.user = userDTOService.toDTO(bookmark.getUser(), depth);
            dto.warehouse = warehouseDTOService.toDTO(bookmark.getWarehouse(), depth);
        }

        return dto;
    }

    /**
     * Converts the passed dto to a Bookmark.
     * Convenient for query by example.
     */
    public Bookmark toEntity(BookmarkDTO dto) {
        return toEntity(dto, 1);
    }

    /**
     * Converts the passed dto to a Bookmark.
     * Convenient for query by example.
     */
    public Bookmark toEntity(BookmarkDTO dto, int depth) {
        if (dto == null) {
            return null;
        }

        Bookmark bookmark = new Bookmark();

        bookmark.setId(dto.id);
        bookmark.setCreationDate(dto.creationDate);
        bookmark.setCreationAuthor(dto.creationAuthor);
        bookmark.setLastModificationDate(dto.lastModificationDate);
        bookmark.setLastModificationAuthor(dto.lastModificationAuthor);
        bookmark.setVersion(dto.version);
        if (depth-- > 0) {
            bookmark.setUser(userDTOService.toEntity(dto.user, depth));
            bookmark.setWarehouse(warehouseDTOService.toEntity(dto.warehouse, depth));
        }

        return bookmark;
    }
}