/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.mycompany.myapp.dto;


/**
 * Simple DTO for Warehouse.
 */
public class WarehouseSearchResultsDTO {
	
	
	public Integer id;
    public String name;
    public Double rating;
    public Integer facilitySize;
    public String facilitySizeUom;
    public Integer storageSize;
    public String storageSizeUom;
    public Double storagePrice;
    public String storagePriceUom;
    public String lat;
    public String lng;

}