//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//
import {WarehouseGoodsPk} from "./warehouseGoodsPk";
import {Goods} from '../goods/goods';
import {Warehouse} from '../warehouse/warehouse';

export class WarehouseGoods {
    id : WarehouseGoodsPk = new WarehouseGoodsPk();
    // Raw attributes
    creationDate : Date;
    creationAuthor : string;
    lastModificationDate : Date;
    lastModificationAuthor : string;
    version : number;
    // x-to-one
    typeOfGoods : Goods;
    warehouse : Warehouse;


    constructor(json? : any) {
        if (json != null) {
            this.id = new WarehouseGoodsPk(json.id);
            if (json.creationDate != null) {
                this.creationDate = new Date(json.creationDate);
            }
            this.creationAuthor = json.creationAuthor;
            if (json.lastModificationDate != null) {
                this.lastModificationDate = new Date(json.lastModificationDate);
            }
            this.lastModificationAuthor = json.lastModificationAuthor;
            this.version = json.version;

            if (json.typeOfGoods != null) {
                this.typeOfGoods = new Goods(json.typeOfGoods);
            }

            if (json.warehouse != null) {
                this.warehouse = new Warehouse(json.warehouse);
            }
        }
    }

    // Utils

    static toArray(jsons : any[]) : WarehouseGoods[] {
        let warehouseGoodss : WarehouseGoods[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                warehouseGoodss.push(new WarehouseGoods(json));
            }
        }
        return warehouseGoodss;
    }
}
