//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//

export class Record {
    // Raw attributes
    id : number;
    data : string;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.data = json.data;
        }
    }

    // Utils

    static toArray(jsons : any[]) : Record[] {
        let records : Record[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                records.push(new Record(json));
            }
        }
        return records;
    }
}
