//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { Record } from './record';
import { Observable } from 'rxjs/Rx';
import { catchError, map } from 'rxjs/operators';
import 'rxjs/add/observable/throw';

@Injectable()
export class RecordService {

    constructor(private http: HttpClient, private messageService : MessageService) {}

    /**
     * Get a Record by id.
     */
    getRecord(id : any) : Observable<Record> {
        return this.http.get('/api/records/' + id)
            .pipe(
                map(response => new Record(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Update the passed record.
     */
    update(record : Record) : Observable<Record> {
        let body = record;

        return this.http.put('/api/records/', body)
            .pipe(
                map(response => new Record(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Load a page (for paginated datatable) of Record using the passed
     * record as an example for the search by example facility.
     */
    getPage(record : Record, event : LazyLoadEvent) : Observable<PageResponse<Record>> {
        let req = new PageRequestByExample(record, event);
        let body = req;

        return this.http.post<PageResponse<any>>('/api/records/page', body)
            .pipe(
                map(pr =>  new PageResponse<Record>(pr.totalPages, pr.totalElements, Record.toArray(pr.content))),
                catchError(this.handleError)
            );
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by RecordCompleteComponent.
     */
    complete(query : string) : Observable<Record[]> {
        let body = {'query': query, 'maxResults': 10};
        return this.http.post<any[]>('/api/records/complete', body)
            .pipe(
                map(response => Record.toArray(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Delete an Record by id.
     */
    delete(id : any) {
        return this.http.delete('/api/records/' + id)
            .pipe(catchError(this.handleError));
    }

    // sample method from angular doc
    private handleError (error: HttpErrorResponse) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message : 'Server error';
        console.error(errMsg);
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
